# <h1>DATA ACQUISITION</h1>

<h1>1. Starting with Json data</h1>

In [3]:
import pandas as pd

import warnings
warnings.filterwarnings("ignore")

In [4]:
df = pd.read_json("test.json")

In [5]:
df.head()

      id                                        ingredients
0  18009  [baking powder, eggs, all-purpose flour, raisi...
1  28583  [sugar, egg yolks, corn starch, cream of tarta...
2  41580  [sausage links, fennel bulb, fronds, olive oil...
3  29752  [meat cuts, file powder, smoked sausage, okra,...
4  35687  [ground black pepper, salt, sausage casings, l...

In [6]:
df.columns

Index(['id', 'ingredients'], dtype='object')

In [10]:
df.ingredients[0][0]

'baking powder'

In [11]:
#df = pd.read_json(url)

**Conclusion : json to dataframe , now u can apply EDA or all the step**

# 2. SQL data

In [ ]:
# !pip install mysql.connector
# run this if not installed

Collecting mysql.connector
  Using cached mysql-connector-2.2.9.tar.gz (11.9 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: mysql.connector
  Building wheel for mysql.connector (pyproject.toml): started
  Building wheel for mysql.connector (pyproject.toml): finished with status 'done'
  Created wheel for mysql.connector: filename=mysql_connector-2.2.9-cp310-cp310-win_amd64.whl size=248050 sha256=735b8c9898be2ca7fae13415f419d689a7a662a79acf4a97bfd34557132b2139
  Stored in directory: c:\users\blbon\appdata\local\pip\cache\wheels\76\48\9b\da67ff1a18fe8e9d428f9b1a177716d4a7d363d2bbe83bf6cf
Successfully built mysql.connector
Installing collected packages: mysql.connector
Successfully installed mysql.connector-2.2.9

In [15]:
import mysql.connector

In [17]:
conn = mysql.connector.connect(host = 'localhost', user = 'root', password = '', database = 'world')

In [27]:
pd.read_sql_query("SHOW TABLES", conn)

   Tables_in_world
0             city
1          country
2  countrylanguage

In [19]:
df_city = pd.read_sql_query("SELECT * FROM city", conn)

In [20]:
df_city.head()

   ID            Name CountryCode       District  Population
0   1           Kabul         AFG          Kabol     1780000
1   2        Qandahar         AFG       Qandahar      237500
2   3           Herat         AFG          Herat      186800
3   4  Mazar-e-Sharif         AFG          Balkh      127800
4   5       Amsterdam         NLD  Noord-Holland      731200

In [23]:
df_country = pd.read_sql_query("SELECT * FROM country", conn)

In [24]:
df_country.head()

,Code,Name,Continent,Region,SurfaceArea,IndepYear,Population,LifeExpectancy,GNP,GNPOld,LocalName,GovernmentForm,HeadOfState,Capital,Code2
0,ABW,Aruba,North America,Caribbean,193.0,NaN,103000,78.4,828.0,793.0,Aruba,Nonmetropolitan Territory of The Netherlands,Beatrix,129.0,AW
1,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF
2,AGO,Angola,Africa,Central Africa,1246700.0,1975.0,12878000,38.3,6648.0,7984.0,Angola,Republic,José Eduardo dos Santos,56.0,AO
3,AIA,Anguilla,North America,Caribbean,96.0,NaN,8000,76.1,63.2,NaN,Anguilla,Dependent Territory of the UK,Elisabeth II,62.0,AI
4,ALB,Albania,Europe,Southern Europe,28748.0,1912.0,3401200,71.6,3205.0,2500.0,Shqipëria,Republic,Rexhep Mejdani,34.0,AL

# 3. Data acquisition using APIs

API :- application programming interface, used to interface two software or it is a data pipeline

In [28]:
# use rapid api to get data from api and convert it to dataframe

In [ ]:
# !pip install requests

In [39]:
import requests

url = "https://imdb232.p.rapidapi.com/api/actors/get-related-news"

querystring = {"limit":"25","nm":"nm0366389"}

headers = {
	"x-rapidapi-key": "2d47fc40b3msh5a8e62db2fa524fp1439dfjsn44bc58ccf4d0",
	"x-rapidapi-host": "imdb232.p.rapidapi.com",
	"Content-Type": "application/json"
}

response = requests.get(url, headers=headers, params=querystring)

print(response.json())

{'data': {'name': {'id': 'nm0366389', 'nameText': {'text': 'Kevin Hart'}, 'news': {'__typename': 'NewsConnection', 'edges': [{'node': {'__typename': 'News', 'id': 'ni65833114', 'byline': None, 'date': '2026-05-09T15:00:10Z', 'externalUrl': 'https://www.tvinsider.com/1262344/best-worst-celebrity-roasts/', 'articleTitle': {'plainText': 'Best & Worst Celebrity Roasts Ever: Bob Saget, Pamela Anderson, Justin Bieber & More'}, 'image': {'__typename': 'Image', 'id': 'rm1120651522', 'url': 'https://m.media-amazon.com/images/M/MV5BZGFmZmIzMDktZDc1NC00NDY1LTk2OWUtMmFlNzA1Yzg0YzZlXkEyXkFqcGc@._V1_.jpg', 'height': 570, 'width': 1014}, 'text': {'plainText': 'Expect long set-ups and short punchlines on Netflix this Sunday (May 10) as the streamer airs The Roast of Kevin Hart live. Kevin Hart has put up with put-downs about his stature before as he helped roast Justin Bieber and Tom Brady, but now he’s in the crosshairs, and we’ll see how many of Sunday’s guests pick on his height. We’ll also have to wait and see how good the special will even be because, as you can see below, not every roast has been fire. Drawing from archival clips and online consensus, we’re presenting our picks for the best and worst celebrity roasts from TV history.'}, 'source': {'homepage': {'url': 'https://www.tvinsider.com/', 'label': 'TV Insider'}, 'description': None}}}, {'node': {'__typename': 'News', 'id': 'ni65831664', 'byline': 'Scott Feinberg', 'date': '2026-05-08T12:00:00Z', 'externalUrl': 'https://www.hollywoodreporter.com/movies/movie-news/cannes-sandra-huller-thr-awards-chatter-pod-guest-1236587142/', 'articleTitle': {'plainText': 'Cannes: Sandra Hüller, Star of Competition Film ‘Fatherland,’ Will Guest on THR’s ‘Awards Chatter’ Pod Live From Palais'}, 'image': {'__typename': 'Image', 'id': 'rm1192413186', 'url': 'https://m.media-amazon.com/images/M/MV5BYTQ5YWE1MjYtOTNmYS00MmI4LWExMDItNGY5ZjIyZjIzMzZmXkEyXkFqcGc@._V1_.jpg', 'height': 200, 'width': 200}, 'text': {'plainText': 'The Hollywood Reporter and Campari are pleased to invite attendees of the upcoming Cannes Film Festival to a very special event: a live recording of THR’s Awards Chatter podcast, hosted by yours truly, with Sandra Hüller, the Oscar-nominated German actress.\n\nThe event, which will take place on Friday, May 15, at 11:30 am local time in the exclusive Campari Lounge within the Palais, will feature an hourlong career-retrospective conversation, followed by a reception.\n\nGiven the venue’s limited space, those wishing to attend are encouraged to RSVP via this link as soon as possible.\n\nHüller shot to international fame as the star of two 2023 films that won top prizes at Cannes en route to best picture Oscar nominations, Anatomy of a Fall and The Zone of Interest, garnering a best actress Oscar nom for the former. Remarkably, she is having an even bigger 2026. In February, she was awarded the Berlin'}, 'source': {'homepage': {'url': 'http://www.hollywoodreporter.com/topic/movies', 'label': 'The Hollywood Reporter - Movie News'}, 'description': None}}}, {'node': {'__typename': 'News', 'id': 'ni65827661', 'byline': 'Christopher Hudspeth', 'date': '2026-05-07T20:40:53Z', 'externalUrl': 'https://www.netflix.com/tudum/features/the-roast-of-kevin-hart-live-on-netflix', 'articleTitle': {'plainText': 'The Roast of Kevin Hart Lineup, Tickets Start Time, How to Watch'}, 'image': {'__typename': 'Image', 'id': 'rm4135438338', 'url': 'https://m.media-amazon.com/images/M/MV5BNmVmN2FjM2EtNzg0Mi00ODM4LWJlNTUtODBjOTcwOGYzOTA4XkEyXkFqcGc@._V1_.jpg', 'height': 584, 'width': 1200}, 'text': {'plainText': 'It’s almost time for the roast master to become the roasted. After years of dominating stages and box offices with his comedy, Kevin Hart — who hosted The Roast of Tom Brady back in 2024 and is fresh off discovering the next great comedian on Funny Af with Kevin Hart — will find his feet being held to the fire, surrendering the mic to a roomful of flamethrowers for The Roast of Kevin Hart.\n\nHosted by Shane Gillis, who’s no stranger to walking the tightrope between brutal and hilarious, this live comedy spectacle is sure to be a full-blown cultural moment brimming with hard-hitting jokes. Given Hart’s history of relentlessly roasting his peers,'}, 'source': {'homepage': {'url': 'https://www.netflix.com/tudum', 'label': 'Tudum - Netflix'}, 'description': None}}}, {'node': {'__typename': 'News', 'id': 'ni64989107', 'byline': 'Alexis Mikulski Ruiz and Oscar Hartzog', 'date': '2026-05-06T23:26:43Z', 'externalUrl': 'https://www.rollingstone.com/product-recommendations/lifestyle/best-digital-gifts-1235190800/', 'articleTitle': {'plainText': 'These Digital Gifts Can Be Ordered Online and Delivered Instantly for Mother’s Day'}, 'image': {'__typename': 'Image', 'id': 'rm1865205762', 'url': 'https://m.media-amazon.com/images/M/MV5BNzZhODU5OWUtNmZmNC00N2NiLTlmNDYtOGYxNTRiYjExMWI5XkEyXkFqcGc@._V1_.jpg', 'height': 150, 'width': 150}, 'text': {'plainText': 'If you purchase an independently reviewed product or service through a link on our website, Rolling Stone may receive an affiliate commission.\n\nYou love the mom or mother figure in your life — I know that, otherwise you wouldn’t have clicked on this article. But your presence here also tells me something else: Mother’s Day may have snuck up on you a little faster than expected. Officially falling on Sunday, May 10, we’re now dangerously close to the holiday dedicated to reminding the special woman in your life how great she really is.'}, 'source': {'homepage': {'url': 'http://www.rollingstone.com/', 'label': 'Rollingstone.com'}, 'description': None}}}, {'node': {'__typename': 'News', 'id': 'ni65829199', 'byline': 'Naser Nahandian', 'date': '2026-05-06T20:08:09Z', 'externalUrl': 'https://gazettely.com/2026/05/entertainment/ron-taylor-wins-funny-af-kevin-hart-netflix-stand-up-special/', 'articleTitle': {'plainText': 'Ron Taylor Crowned Winner of Netflix’s Funny Af, Lands His Own Stand-Up Special'}, 'image': {'__typename': 'Image', 'id': 'rm1012122624', 'url': 'https://m.media-amazon.com/images/M/MV5BMzUwMzUxMjcxMV5BMl5BanBnXkFtZTgwNzA3Mzg3MjE@._V1_.jpg', 'height': 375, 'width': 500}, 'text': {'plainText': 'Detroit-born comedian Ron Taylor has won the first season of Funny Af with Kevin Hart, beating out a field of more than 40 comics to claim a Netflix stand-up special and a coveted spot at the streamer’s most high-profile comedy event of the year.\n\nTaylor was crowned during a live finale that aired Tuesday night on Netflix, with subscribers around the world casting real-time votes to determine the outcome. He prevailed over three finalists — Caitlin Peluffo, Usama Siddiquee, and Reg Thomas — in a competition that Hart said left him genuinely stunned. “Ron is such an amazing talent, he has a strong voice and I love his energy,” Hart said. “He is poised,'}, 'source': {'homepage': {'url': 'https://gazettely.com/', 'label': 'Gazettely'}, 'description': None}}}, {'node': {'__typename': 'News', 'id': 'ni65829020', 'byline': 'Matt Grobar', 'date': '2026-05-06T18:56:32Z', 'externalUrl': 'https://deadline.com/2026/05/ron-taylor-wins-funny-af-kevin-hart-1236883383/', 'articleTitle': {'plainText': 'Ron Taylor Wins Kevin Hart’s Netflix Comedy Competition Series ‘Funny Af’'}, 'image': {'__typename': 'Image', 'id': 'rm3427846146', 'url': 'https://m.media-amazon.com/images/M/MV5BMGMwYjBjZDQtM2VmMy00MTMxLWE1ZDgtYTU4NDY2NWJmYWI4XkEyXkFqcGc@._V1_.jpg', 'height': 2400, 'width': 3600}, 'text': {'plainText': '34-year-old Detroit-born comic Ron Taylor has been declared the winner of Funny Af with Kevin Hart, Netflix’s comedy competition series which wrapped its first season last night.\n\nTaylor prevailed over comics including Caitlin Peluffo, Usama Siddiquee, and Reg Thomas.\n\nHart said of the accomplishment, “Ron is such an amazing talent, he has a strong voice and I love his energy. He is poised, polished, and now positioned to be a face that we will be seeing for quite some time. This competition was everything it was supposed to be plus more. The four finalists were all amazing – they did not disappoint. I am blown away at Ron’s win and we are all in full celebration mode.”\n\nTaylor was crowned winner of Funny Af during a taping on Tuesday night, for an episode that aired live. As winner, he’ll now get his very own Netflix special, which he'}, 'source': {'homepage': {'url': 'http://www.deadline.com/', 'label': 'Deadline Film + TV'}, 'description': None}}}, {'node': {'__typename': 'News', 'id': 'ni65805325', 'byline': 'Tudum Staff', 'date': '2026-05-06T15:18:56Z', 'externalUrl': 'https://www.netflix.com/tudum/articles/funny-af-season-1-cast-instagrams-finalists', 'articleTitle': {'plainText': 'Who Won Funny Af with Kevin Hart? Ron Taylor Takes the Title'}, 'image': {'__typename': 'Image', 'id': 'rm1985595394', 'url': 'https://m.media-amazon.com/images/M/MV5BMzc2YTI5ZGQtNjZlOC00NWNkLWJhNDAtMWZhM2EwYTVkZDJmXkEyXkFqcGc@._V1_.jpg', 'height': 675, 'width': 1200}, 'text': {'plainText': 'After weeks of showcases, callbacks, and sets across the country’s most iconic comedy clubs, Funny Af with Kevin Hart has its winner.\n\nRon Taylor — the Detroit-born comic known for putting a “silly flair on serious things” — has taken the title, earning a coveted Netflix comedy special and officially stepping into the spotlight as the show’s next breakout star.\n\nThe win marks a major moment for Taylor, who has spent years refining his voice onstage, from learning timing and structure as a teenager to becoming a paid regular at the world-famous Comedy Store in Los Angeles. Handpicked by Bill Burr for Comedy Central’s The Ringers, Taylor entered the'}, 'source': {'homepage': {'url': 'https://www.netflix.com/tudum', 'label': 'Tudum - Netflix'}, 'description': None}}}, {'node': {'__typename': 'News', 'id': 'ni65757751', 'byline': 'Amanda Richards', 'date': '2026-05-06T02:52:03Z', 'externalUrl': 'https://www.netflix.com/tudum/features/funny-af-with-kevin-hart-how-to-vote-judges-cast', 'articleTitle': {'plainText': 'Funny Af with Kevin Hart: Winner, Judges, Finale, and More'}, 'image': {'__typename': 'Image', 'id': 'rm479645954', 'url': 'https://m.media-amazon.com/images/M/MV5BZmQ3NGRlNTgtMjk3Ny00ZjRiLWE3ZTktYjBhZmRkNTQzZjdkXkEyXkFqcGc@._V1_.jpg', 'height': 675, 'width': 1200}, 'text': {'plainText': 'Kevin Hart set out to discover the next great stand-up comic — and after weeks of challenges, live performances, and audience voting, Funny Af with Kevin Hart officially crowned its first winner.\n\nThe Netflix comedy competition series brought together rising comedians from across the country alongside a rotating panel of comedy heavyweights, including Keegan-Michael Key, Tom Segura, Kumail Nanjiani, Chelsea Handler, and Nikki Glaser.\n\nOver the course of the season, contestants faced the realities of life as a stand-up comic, from high-pressure sets and rewrites to live performances in front of massive audiences. The competition ultimately culminated in two live episodes, where Netflix members voted in real time to help decide'}, 'source': {'homepage': {'url': 'https://www.netflix.com/tudum', 'label': 'Tudum - Netflix'}, 'description': None}}}, {'node': {'__typename': 'News', 'id': 'ni65827707', 'byline': 'Erik Hayden', 'date': '2026-05-05T23:46:14Z', 'externalUrl': 'https://www.hollywoodreporter.com/business/business-news/hasbro-entertainment-team-west-hollywood-1236587026/', 'articleTitle': {'plainText': 'Hasbro’s Entertainment Team Moving to West Hollywood'}, 'image': {'__typename': 'Image', 'id': 'rm4202612738', 'url': 'https://m.media-amazon.com/images/M/MV5BYTVlZTZiMDUtM2Q3Yy00YzQ0LWJhYTItYWZhNmYyMDMyMzcyXkEyXkFqcGc@._V1_.jpg', 'height': 200, 'width': 200}, 'text': {'plainText': 'Another entertainment company is on the move to West Hollywood.\n\nHasbro is planning to relocate 100 employees that work across film, TV, gaming, licensing, toys and its AI studio to The Lot at Formosa in the first quarter of next year. The company inked a long-term lease for 31,435 square feet on the third floor and part of the fourth floor at the Formosa West office building.\n\nThe firm will vacate its lease on Empire Ave in Burbank, where it had been occupying 80,000 square feet of office space that housed its consumer products and entertainment segments, per a regulatory filing.\n\nHasbro will join Miramax, Live Nation, People Inc. and Kevin Hart’s banner Hartbeat on The Lot, an 11-acre campus owned by Cim Group that also touts seven soundstages.\n\n“This move marks a new chapter for Hasbro, bringing our teams into the heart of West Hollywood and closer to the partners we collaborate with every day,'}, 'source': {'homepage': {'url': 'http://www.hollywoodreporter.com/topic/movies', 'label': 'The Hollywood Reporter - Movie News'}, 'description': None}}}, {'node': {'__typename': 'News', 'id': 'ni65827692', 'byline': 'Joe Roberts', 'date': '2026-05-05T23:00:00Z', 'externalUrl': 'https://www.slashfilm.com/2161455/william-shatner-eddie-murphy-comedy-showtime/', 'articleTitle': {'plainText': 'William Shatner Played Himself In This Eddie Murphy Comedy That Critics Tore To Shreds'}, 'image': {'__typename': 'Image', 'id': 'rm2726217730', 'url': 'https://m.media-amazon.com/images/M/MV5BMjdkNDMwMjItYTEzNi00Yjk0LTgxZmQtMjgwODI4ZGQwMjhmXkEyXkFqcGc@._V1_.jpg', 'height': 438, 'width': 780}, 'text': {'plainText': 'Warner Bros. is, in my opinion, the greatest studio ever. Recent buyout debacles aside, this is the studio that gave us "Blade Runner," the great films of Stanley Kubrick, Elia Kazan\'s "A Streetcar Named Desire," and established the superhero blockbusters with Richard Donner\'s "Superman." But even Harry, Jack, Albert, and Sam Warner\'s storied studio has churned out some tripe in its time, and 2002 action comedy "Showtime" is one example. At least, according to critics who savaged this Eddie Murphy and Robert De Niro-led buddy cop outing, despite it featuring a delightful cameo from the great William Shatner, playing himself.\n\nThe comedy debuted following a nice little late-\'90s run for Murphy,'}, 'source': {'homepage': {'url': 'http://www.slashfilm.com', 'label': 'Slash Film'}, 'description': None}}}, {'node': {'__typename': 'News', 'id': 'ni65827618', 'byline': 'Matthew Rudoy', 'date': '2026-05-05T21:16:34Z', 'externalUrl': 'https://screenrant.com/lord-of-the-flies-netflix-streaming-success-may-2026/', 'articleTitle': {'plainText': 'Netflix’s Stephen King-Approved Adaptation Of 72-Year-Old Survival Thriller Takes America By Storm'}, 'image': {'__typename': 'Image', 'id': 'rm2189215746', 'url': 'https://m.media-amazon.com/images/M/MV5BZTM2YmVjMmItYjhhNS00M2I0LTllMDAtYjE2M2ZlZjhiOTA2XkEyXkFqcGc@._V1_.jpg', 'height': 1080, 'width': 1920}, 'text': {'plainText': "A 72-year-old survival thriller adaptation approved by Stephen King is taking Netflix by storm.\n\nAs one of the most popular and successful authors, whose works have been turned into numerous movie and television adaptations, King's positive reviews of other media speak volumes. He has previously praised FX's Alien: Earth, Hulu's Paradise, MGM+'s From, Apple TV's Silo, and Netflix's Stranger Things, with his words bringing further recognition to these series that belong to the science-fiction and horror genres.\n\nNow, the latest Stephen King-approved show, Lord of the Flies, is dominating Netflix in the United States. Only one day after the four-episode miniseries came to the streaming platform,"}, 'source': {'homepage': {'url': 'http://screenrant.com/', 'label': 'ScreenRant'}, 'description': None}}}, {'node': {'__typename': 'News', 'id': 'ni65830388', 'byline': 'Caroline Preece', 'date': '2026-05-04T16:32:42Z', 'externalUrl': 'https://movieweb.com/kevin-hart-netflix-spy-action-comedy-mcg/', 'articleTitle': {'plainText': 'Kevin Hart To Star in Netflix Spy Action Comedy Directed by McG'}, 'image': {'__typename': 'Image', 'id': 'rm2083899394', 'url': 'https://m.media-amazon.com/images/M/MV5BYzYxZTE1NzItMmQ1MS00ZDBmLTkyNDktZmZlOTBkYTYyOTM0XkEyXkFqcGc@._V1_.jpg', 'height': 1080, 'width': 1920}, 'text': {'plainText': 'Netflix is adding another star-led action comedy to its slate, this time with a premise that sounds engineered for one-line appeal and the broadest streaming reach possible. The untitled project will reportedly mix espionage, domestic hijinks, and a filmmaker whose name is closely tied to polished studio action.\n\nAccording to The Hollywood Reporter, Kevin Hart is set to lead an untitled "high-concept" spy action comedy for Netflix, with McG attached to direct. McG is, of course, best known for movies like Charlie\'s Angels and Terminator Salvation, making this a pretty obvious return to the large-scale action setups that first defined his career.\n\nThe hook is simple but solid, with a'}, 'source': {'homepage': {'url': 'http://www.movieweb.com', 'label': 'MovieWeb'}, 'description': None}}}, {'node': {'__typename': 'News', 'id': 'ni65779102', 'byline': 'Marcus James Dixon', 'date': '2026-05-04T16:29:00Z', 'externalUrl': 'https://www.goldderby.com/tv/2026/2026-emmys-fyc-event-calendar-dates-awards/', 'articleTitle': {'plainText': '2026 Emmys FYC calendar: ‘Outlander,’ ‘The Audacity,’ and more events geared to wooing voters'}, 'image': {'__typename': 'Image', 'id': 'rm1938999810', 'url': 'https://m.media-amazon.com/images/M/MV5BZTNmOTRhZmUtMGJiNi00OGU4LWE4Y2EtMGFmMTU4ODI4YmEwXkEyXkFqcGc@._V1_.jpg', 'height': 150, 'width': 150}, 'text': {'plainText': 'This year\'s Emmy "For Your Consideration" season officially kicked off on March 2 and ends June 10. It\'s the time of year when networks and studios fully engage with Television Academy members in Los Angeles and New York by offering screenings, Q&As, receptions, and more events featuring the biggest awards contenders. Some Emmy voters show up hoping to snap photos with the stars, others are just there for the free food and drinks.\n\nIn recent years, streamers like Netflix, Prime Video, and Hulu hosted fully immersive FYC houses encapsulating all their respective projects campaigning in a given cycle. However, as Gold Derby reported, those companies have pulled back on Emmy popups this season,'}, 'source': {'homepage': {'url': 'http://www.goldderby.com', 'label': 'Gold Derby'}, 'description': None}}}, {'node': {'__typename': 'News', 'id': 'ni65825154', 'byline': 'Ethan Shanfeld', 'date': '2026-05-04T14:42:24Z', 'externalUrl': 'https://variety.com/2026/tv/news/netflix-comedy-execs-louis-ck-backlash-tim-robinson-1236736358/', 'articleTitle': {'plainText': 'Netflix Comedy Chiefs on Netflix Is a Joke Fest, Louis C.K. Backlash and the Future of ‘I Think You Should Leave,’ ‘Everybody’s Live’ and More'}, 'image': {'__typename': 'Image', 'id': 'rm2880489474', 'url': 'https://m.media-amazon.com/images/M/MV5BZmI3NGU0NzctYmI2Yy00MTJhLWI1ODAtYmM2MTQ5NTJlNDUyXkEyXkFqcGc@._V1_.jpg', 'height': 1960, 'width': 2960}, 'text': {'plainText': 'Netflix Is a Joke Fest, the biennial event sprawling across Los Angeles, will be taking over venues like the Greek Theatre, Intuit Dome and The Comedy Store from May 4 to 10. Think of a currently performing comic, and they’re probably on the lineup: Shane Gillis hosts a roast of Kevin Hart; John Mulaney headlines the Hollywood Bowl; Flight of the Conchords reunites. They’re joined by Nikki Glaser, Jerry Seinfeld, Katt Williams and many more.\n\nThe event is a victory lap for the streamer — which has become the most prominent name in stand-up — as well as a reflection of the talent it has partnered with on the scripted side. Here, Netflix stand-up chief Robbie Praw and scripted comedy boss Tracey Pakosta talk about curating the festival and what’s next on Netflix.\n\nWhat do you think is the wackiest or most ambitious idea you will pull off this year?\n\nRobbie Praw'}, 'source': {'homepage': {'url': 'http://variety.com/', 'label': 'Variety Film + TV'}, 'description': None}}}, {'node': {'__typename': 'News', 'id': 'ni65825138', 'byline': 'Ariane Cruz', 'date': '2026-05-04T

In [45]:
df = pd.DataFrame(response.json())

In [46]:
df.head()

                                                   data
name  {'id': 'nm0366389', 'nameText': {'text': 'Kevi...

In [48]:
len(df.data)

1

# 4. Data Aquisition using Web Scrapng